//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtPrax.WebApp.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GtPrax.WebApp.I18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interner Fehler beim Anlegen des Datensatzes..
        /// </summary>
        internal static string InternalErrorCreateRecord {
            get {
                return ResourceManager.GetString("InternalErrorCreateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interner Fehler beim Speichern des Datensatzes..
        /// </summary>
        internal static string InternalErrorUpdateRecord {
            get {
                return ResourceManager.GetString("InternalErrorUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse ist ungültig..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Bestätigen der neuen E-Mail-Adresse ist ungültig oder abgelaufen. Der Vorgang muss wiederholt werden..
        /// </summary>
        internal static string InvalidNewEmailConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidNewEmailConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Bestätigen des neuen Passwortes ist ungültig oder abgelaufen. Der Vorgang muss wiederholt werden..
        /// </summary>
        internal static string InvalidPasswordResetLink {
            get {
                return ResourceManager.GetString("InvalidPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link zum Bestätigen der Registrierung ist ungültig oder abgelaufen. Der Vorgang muss wiederholt werden..
        /// </summary>
        internal static string InvalidRegisterConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidRegisterConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anfrage ist ungültig..
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Warteliste wurde nicht gefunden..
        /// </summary>
        internal static string WaitlistNotFound {
            get {
                return ResourceManager.GetString("WaitlistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Patient wurde in der Warteliste nicht gefunden..
        /// </summary>
        internal static string WaitlistPatientNotFound {
            get {
                return ResourceManager.GetString("WaitlistPatientNotFound", resourceCulture);
            }
        }
    }
}
