<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SQLite" />
    <PackageReference Include="MessagePack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GtPrax.WebApp\GtPrax.WebApp.csproj" />
  </ItemGroup>

</Project>
